# Generated by Django 5.1.5 on 2025-02-13 15:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book_outlet", "0002_book_is_bestselling_alter_book_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
